### ISSUE TITLE
All (*) element styling is too specific

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#8]
## Current status

In `/style.css` the selector `*` contains a lot of specific global styling. In large projects, this will affect a lot of elements.

``` css

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'nunito';
    overflow: hidden;
}

```

## Nice to have

``` css

*, *::after, *::before {
    box-sizing: border-box;
}

body {
    margin: 0;
    padding: 0;
    font-family: 'nunito';
}

.containerWithNoOverflow {
    overflow: hidden;
}
```
